import React from 'react'
type User={id:number;name:string;role:string;permissions?:string[]}
const roleLinks:Record<string,[string,string,string][]>={
admin:[['/','▦','Cashier'],['/waiter','☰','Waiter'],['/kitchen','♨','Kitchen'],['/tables','▤','Tables'],['/customer-display','▣','Display'],['/admin','⚙','Admin']],
manager:[['/','▦','Cashier'],['/waiter','☰','Waiter'],['/kitchen','♨','Kitchen'],['/tables','▤','Tables'],['/admin','⚙','Admin']],
cashier:[['/','▦','Cashier'],['/tables','▤','Tables'],['/customer-display','▣','Display']],
waiter:[['/waiter','☰','Waiter'],['/tables','▤','Tables']],kitchen:[['/kitchen','♨','Kitchen']]}
function currentUser():User|null{try{return JSON.parse(localStorage.getItem('mahi_user')||'null')}catch{return null}}
export default function Shell({title,subtitle,children,compact=false}:{title:string;subtitle?:string;children:React.ReactNode;compact?:boolean}){const path=location.pathname,user=currentUser(),role=user?.role||'cashier',links=roleLinks[role]||roleLinks.cashier;const logout=()=>{localStorage.removeItem('mahi_user');location.href='/login'};return <div className="app-shell"><aside className="side-nav"><div className="brand"><div className="brand-mark">M</div><div><strong>MAHI POS</strong><span>Restaurant System</span></div></div><nav>{links.map(([href,icon,label])=>{const active=href==='/'?path==='/' : path.startsWith(href);return <a className={active?'active':''} href={href} key={href}><i>{icon}</i><span>{label}</span></a>})}</nav><div className="side-user"><div className="side-avatar">{(user?.name||'U')[0]}</div><div><b>{user?.name||'User'}</b><span>{role}</span></div></div><button className="logout-btn" onClick={logout}>Log out</button><div className="side-footer"><span className="live-dot"></span>System Online</div></aside><section className="app-main"><header className="topbar"><div><h1>{title}</h1>{subtitle&&<p>{subtitle}</p>}</div><div className="top-actions"><span className="terminal-pill">{user?.name||'Terminal 01'}</span><span className="clock">{new Date().toLocaleDateString('en-GB')}</span></div></header><div className={compact?'page compact':'page'}>{children}</div></section></div>}
